version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: postgresdb
    env_file:
      - .env
    volumes:
    - ./data/db:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  pgadminer:
    container_name: pgadminer
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_USER}@postgres.com
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - 8080:80
  flyway:
      container_name: flyway
      env_file:
        - .env
      environment:
        - FLYWAY_USER=${POSTGRES_USER}
        - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
        - FLYWAY_URL=jdbc:postgresql://db:${POSTGRES_PORT}/${POSTGRES_DB}
        - FLYWAY_SCHEMAS=flyway,${POSTGRES_SCHEMA}
        - FLYWAY_GROUP=true
      image: flyway/flyway:latest
      command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
      volumes:
        - $PWD/sql_versions:/flyway/sql
      depends_on:
        - db